### ISSUE TITLE
Invisible menu items

### ISSUE THREAD

**Issue by igreenman** [htrb/ngraph-gtk#3]
Menu items are not fully visible until you hover over them (on the screenshot).

In the main (top) menu, everything is fine.
```
$ ngraph -V
(Ngraph): configuration 'file_win' in section [x11menu] is not used.
(Ngraph): configuration 'axis_win' in section [x11menu] is not used.
(Ngraph): configuration 'legend_win' in section [x11menu] is not used.
(Ngraph): configuration 'merge_win' in section [x11menu] is not used.
(Ngraph): configuration 'coordinate_win' in section [x11menu] is not used.
(Ngraph): configuration 'information_win' in section [x11menu] is not used.
(Ngraph): configuration 'palette' in section [x11menu] is not used.
(Ngraph): configuration 'single_window_mode' in section [x11menu] is not used.
Ngraph version 6.09.01
Copyright (C) 2003, Satoshi ISHIZAKA.

  compiler:
    gcc 10.2.0

  library:
    GTK+
     compile: 3.24.24
      linked: 3.24.24

    GLib
     compile: 2.66.4
      linked: 2.66.4

    Cairo
     compile: 1.17.4
      linked: 1.17.4

    Pango
     compile: 1.48.1
      linked: 1.48.1

    GtkSourceView
     compile: 4.8.0
      linked: 4.8.0

    readline
     compile: 8.1
      linked: 8.1

    GSL
     compile: 2.6
      linked: 2.6
```
![ngraph-gtk-screenshot](https://user-images.githubusercontent.com/8288373/106990005-f86ba100-67a5-11eb-96c0-62942c886d8d.png)

Console output during this behavior:
```
(ngraph:38155): Gtk-WARNING **: 11:57:51.236: no trigger event for menu popup
```
OS: Archlinux

**Comment by htrb** [comment]
Thank you for the report.
Unfortunately, I cannot reproduce the  behavior in my environment.
I will check codes related to the popup-menu, however, I suppose the origin of the problem is inside GTK library and will be fixed in the future release of the library.

My environments:
$ ngraph -V
Ngraph version 6.09.01
Copyright (C) 2003, Satoshi ISHIZAKA.

  compiler:
    gcc 10.2.1 20210110

  library:
    GTK+
     compile: 3.24.24
      linked: 3.24.24

    GLib
     compile: 2.66.6
      linked: 2.66.6

    Cairo
     compile: 1.16.0
      linked: 1.16.0

    Pango
     compile: 1.46.2
      linked: 1.46.2

    GtkSourceView
     compile: 4.8.0
      linked: 4.8.0

    readline
     compile: 8.1
      linked: 8.1

    GSL
     compile: 2.6
      linked: 2.6

 $ uname -a
Linux fontana 5.9.0-3-amd64 #1 SMP Debian 5.9.9-1 (2020-11-19) x86_64 GNU/Linux

$ gsettings get org.gnome.desktop.interface gtk-theme                                                                                                                                                               
'Adwaita-dark'

**Comment by igreenman** [comment]
```
$ gsettings get org.gnome.desktop.interface gtk-theme  
'TraditionalOk'
```
I figured out the problem occurs with this theme. With themes 'Adwaita' and 'Adwaita-dark', everything is fine.
